version: "3.9"

services:
  api:
    build:
      context: .
    image: backend-app:latest
    container_name: backend_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    image: backend-app:latest
    container_name: backend_worker
    command: ["node", "dist/worker.js"]
    env_file:
      - .env
    depends_on:
      - redis
    
  kgs:
    image: backend-app:latest
    container_name: backend_kgs
    command: ["node", "dist/kgs.service.js"]
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: backend_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
